// Generates src/generated/api.d.ts from the running apps/api OpenAPI document.
//
// URL resolution (first hit wins): API_OPENAPI_URL (env) > API_PORT (env) >
// API_OPENAPI_URL / API_PORT from the repo-root .env. No port is ever guessed — with nothing set
// the script refuses (use `make gen-types`). The document is fetched first and only written when
// info.title matches apps/api, so another service on the same port can never replace our types.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const EXPECTED_TITLE = "NeuroAI API";
const FETCH_TIMEOUT_MS = 10_000;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoEnv = resolve(root, "../../.env");
const out = resolve(root, "src/generated/api.d.ts");

function fail(message) {
  console.error(`[shared] ${message}`);
  process.exit(1);
}

// Minimal KEY=value parser for the root .env (comments, blank lines, quotes, `export `).
function readDotenv(path) {
  const vars = {};
  if (!existsSync(path)) return vars;
  for (const raw of readFileSync(path, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 1) continue;
    const key = line
      .slice(0, eq)
      .trim()
      .replace(/^export\s+/, "");
    let value = line.slice(eq + 1).trim();
    const quoted = /^(["']).*\1$/.exec(value);
    value = quoted ? value.slice(1, -1) : value.replace(/\s+#.*$/, "");
    vars[key] = value;
  }
  return vars;
}

function resolveUrl() {
  const portUrl = (port) => (port ? `http://localhost:${port}/openapi.json` : "");
  const env = process.env;
  const file = readDotenv(repoEnv);
  const url =
    env.API_OPENAPI_URL || portUrl(env.API_PORT) || file.API_OPENAPI_URL || portUrl(file.API_PORT);
  if (!url) {
    fail(
      `neither API_OPENAPI_URL nor API_PORT is set (env or ${repoEnv}) — refusing to guess a port. ` +
        "Run `make gen-types` from the repo root, or set API_OPENAPI_URL=http://localhost:<API_PORT>/openapi.json",
    );
  }
  return url;
}

async function fetchDocument(url) {
  let res;
  try {
    res = await fetch(url, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
  } catch (err) {
    fail(
      `cannot reach ${url} (${err.cause?.code || err.cause?.message || err.message}) — is the API running? (make dev-api)`,
    );
  }
  if (!res.ok) fail(`${url} answered HTTP ${res.status}`);
  let doc;
  try {
    doc = await res.json();
  } catch {
    fail(`${url} did not return JSON`);
  }
  const title = doc?.info?.title;
  if (title !== EXPECTED_TITLE) {
    const paths = Object.keys(doc?.paths ?? {}).length;
    fail(
      `refusing to write: ${url} serves "${title ?? "?"}" (${paths} paths), expected "${EXPECTED_TITLE}". ` +
        "Another service is listening on that port — check API_PORT / API_OPENAPI_URL (root .env) or run `make gen-types`.",
    );
  }
  return doc;
}

const url = resolveUrl();
console.log(`[shared] openapi-typescript ${url} -> ${out}`);
const doc = await fetchDocument(url);

const { default: openapiTS, astToString } = await import("openapi-typescript");
const ast = await openapiTS(doc);
const header =
  `// Generated by openapi-typescript from ${url} (${doc.info.title} ${doc.info.version ?? ""}).\n` +
  "// Do not edit — regenerate with `make gen-types` (packages/shared/scripts/generate.mjs).\n";

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, header + astToString(ast));
console.log(`[shared] wrote ${out} (${Object.keys(doc.paths ?? {}).length} paths)`);
